### PR TITLE
feat: add get_all_Lending_Proposal function

### PR DESCRIPTION
**Pull request by martinvibes**
hey @Dprof-in-tech kindly review :)

### CODE REVIEW

**Comment by martinvibes** [comment]
ooh ok mistake

**Comment by martinvibes** [comment]
hey @Dprof-in-tech i think i'll wait for #41 to be done with his then i can continue
seems like mine is dependent on his

**Comment by Dprof-in-tech** [comment]
issue solved by #41

**Comment by martinvibes** [comment]
Hi @Dprof-in-tech you've now closed two of my issues that I have done 
And I literally spent most of my time trying to solve the issues 😑

**Pull request closed without merging**
