### PR TITLE
Feat/add counter proposal func

### LINKED ISSUE #42: CONTRACTS:  Build a function to allow users create a counter proposal to a lending proposal
see issue #41  to see what a lending proposal is.

creating a counter proposal is in the situation where a borrower sees a lending proposal that they love but dont want to accept maybe because the number of tokens to be lent is too high or too low, then they can create a proposal to counter it and say, this is the exact things i can take and if the lender is willing, they can move on.

Screenshot 2024-11-21 at 06 36 29

this function should take similar parameters just like in issue #41 and there should also be a read function to read this data after writing it into the blockchain. 

Criteria to be assigned:

follow the guidelines as put in the OD hackers community group.

Please when applying give a reasonable ETA

### PR DESCRIPTION
**Pull request by JoE11-y**
Resolves #42 

Work done
1. Added the counter proposal function.

### CODE REVIEW

**Comment by Dprof-in-tech** [comment]
write the tests for this function so i can merge

**Comment by JoE11-y** [comment]
It's blocked by #41.

**Comment by Dprof-in-tech** [comment]
one minute, let me take a look

**Comment by Dprof-in-tech** [comment]
oh right. please give it an hour, if theres no PR by then, i would reassign

**Comment by JoE11-y** [comment]
Alright 💪

**Review by Dprof-in-tech — APPROVED** [review]

**Pull request merged**
